# Generated by Django 4.0 on 2022-01-25 06:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_alphas', models.CharField(default='', max_length=200)),
                ('start_betas', models.CharField(default='', max_length=200)),
                ('end_alphas', models.CharField(default='', max_length=200)),
                ('end_betas', models.CharField(default='', max_length=200)),
                ('cycle_status', models.CharField(default='inactive', max_length=25)),
                ('n_worker_participated', models.IntegerField(default=2)),
                ('rounds', models.IntegerField(default=100)),
                ('config', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=25, unique=True)),
                ('alphas', models.CharField(default='', max_length=200)),
                ('betas', models.CharField(default='', max_length=200)),
                ('options', models.IntegerField(default=0)),
                ('max_workers', models.IntegerField(default=2)),
                ('status', models.CharField(default='inactive', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCycleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_training_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.globaltrainingcycle')),
            ],
        ),
        migrations.AddField(
            model_name='globaltrainingcycle',
            name='server_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serverdata'),
        ),
    ]
