# Generated by Django 4.0 on 2021-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.CharField(max_length=200)),
                ('beta', models.CharField(max_length=200)),
                ('dim', models.IntegerField(default=0)),
            ],
        ),
    ]
