# Generated by Django 4.0 on 2021-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdata',
            name='group_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='alpha',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='beta',
            field=models.CharField(default='', max_length=200),
        ),
    ]
