# Generated by Django 4.0 on 2021-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serverdata_created_at_serverdata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdata',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
