# Generated by Django 4.0 on 2022-01-10 15:21

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trainingcycle_alter_serverdata_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(max_length=25)),
                ('start_alpha', models.CharField(default='', max_length=200)),
                ('start_beta', models.CharField(default='', max_length=200)),
                ('end_alpha', models.CharField(default='', max_length=200)),
                ('end_beta', models.CharField(default='', max_length=200)),
                ('cycle_status', models.CharField(default='inactive', max_length=25)),
                ('n_worker_participated', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='serverdata',
            old_name='group_name',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='serverdata',
            old_name='dim',
            new_name='options',
        ),
        migrations.DeleteModel(
            name='TrainingCycle',
        ),
        migrations.AddField(
            model_name='globaltrainingcycle',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serverdata'),
        ),
    ]
